name: Build Beamer preview

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Compile LaTeX template
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_shell_escape: true
          latexmk_use_lualatex: false

      - name: Upload compiled PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: hm-beamer-template
          path: main.pdf
          if-no-files-found: error
          retention-days: 7

  preview:
    name: Publish preview to GitHub Pages
    needs: build
    if: vars.ENABLE_PAGES_PREVIEW == 'true' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled PDF
        uses: actions/download-artifact@v4
        with:
          name: hm-beamer-template
          path: preview

      - name: Prepare preview bundle
        env:
          PDF_NAME: main-${{ github.sha }}.pdf
        run: |
          mkdir -p public
          cp preview/main.pdf "public/${PDF_NAME}"
          cat <<EOF > public/index.html
          <!DOCTYPE html>
          <html lang="en">
            <head>
              <meta charset="utf-8" />
              <title>HM Beamer preview</title>
              <style>
                body { font-family: sans-serif; margin: 2rem; }
                iframe { width: 100%; height: 90vh; border: none; }
              </style>
            </head>
            <body>
              <h1>HM Beamer preview</h1>
              <p>
                <a href="./${PDF_NAME}">Download the compiled PDF</a>
                for commit <code>${GITHUB_SHA}</code>.
              </p>
              <iframe src="./${PDF_NAME}" title="Preview PDF"></iframe>
            </body>
          </html>
          EOF

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Post preview link to summary
        env:
          PDF_NAME: main-${{ github.sha }}.pdf
        run: |
          echo "### Preview" >> "$GITHUB_STEP_SUMMARY"
          echo "- [Open the rendered PDF](${{ steps.deploy.outputs.page_url }}${PDF_NAME})" >> "$GITHUB_STEP_SUMMARY"
          echo "- [View the preview page](${{ steps.deploy.outputs.page_url }})" >> "$GITHUB_STEP_SUMMARY"

  preview-disabled:
    name: Skip note for disabled Pages preview
    needs: build
    if: vars.ENABLE_PAGES_PREVIEW != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Explain how to enable Pages preview
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "### Preview" >> "$GITHUB_STEP_SUMMARY"
          echo "- GitHub Pages deployment is currently disabled. Download the \`hm-beamer-template\` artifact to inspect the PDF." >> "$GITHUB_STEP_SUMMARY"
          echo "- To enable direct previews, add a repository variable \`ENABLE_PAGES_PREVIEW\` set to \`true\` and configure GitHub Pages with the \"GitHub Actions\" source under <https://github.com/${REPO}/settings/pages>." >> "$GITHUB_STEP_SUMMARY"
