name: Build Beamer preview

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Compile LaTeX template
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: hm-beamer-template
          path: main.pdf
          if-no-files-found: error
